[2025-03-27T13:00:07.991+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: insert_aqi_to_postgres.fetch_and_insert_aqi scheduled__2025-03-27T12:00:00+00:00 [queued]>
[2025-03-27T13:00:07.997+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: insert_aqi_to_postgres.fetch_and_insert_aqi scheduled__2025-03-27T12:00:00+00:00 [queued]>
[2025-03-27T13:00:07.997+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-03-27T13:00:08.006+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): fetch_and_insert_aqi> on 2025-03-27 12:00:00+00:00
[2025-03-27T13:00:08.010+0000] {standard_task_runner.py:60} INFO - Started process 189 to run task
[2025-03-27T13:00:08.012+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'insert_aqi_to_postgres', 'fetch_and_insert_aqi', 'scheduled__2025-03-27T12:00:00+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/insert_aqi_to_db.py', '--cfg-path', '/tmp/tmplvr4cmve']
[2025-03-27T13:00:08.013+0000] {standard_task_runner.py:88} INFO - Job 38: Subtask fetch_and_insert_aqi
[2025-03-27T13:00:08.023+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-27T13:00:08.043+0000] {task_command.py:423} INFO - Running <TaskInstance: insert_aqi_to_postgres.fetch_and_insert_aqi scheduled__2025-03-27T12:00:00+00:00 [running]> on host deb394d50d01
[2025-03-27T13:00:08.088+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='insert_aqi_to_postgres' AIRFLOW_CTX_TASK_ID='fetch_and_insert_aqi' AIRFLOW_CTX_EXECUTION_DATE='2025-03-27T12:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-27T12:00:00+00:00'
[2025-03-27T13:00:08.544+0000] {insert_aqi_to_db.py:37} INFO - âœ… AQI in Bangkok: 102 at 2025-03-27 13:00:08.544425
[2025-03-27T13:00:08.548+0000] {base.py:83} INFO - Using connection ID 'postgres_conn' for task execution.
[2025-03-27T13:00:08.550+0000] {sql.py:450} INFO - Running statement: 
                INSERT INTO air_quality_data (city, aqi, timestamp_utc)
                VALUES (%s, %s, %s);
            , parameters: ('Bangkok', 102, datetime.datetime(2025, 3, 27, 13, 0, 8, 544425))
[2025-03-27T13:00:08.551+0000] {sql.py:459} INFO - Rows affected: 1
[2025-03-27T13:00:08.551+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-03-27T13:00:08.557+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=insert_aqi_to_postgres, task_id=fetch_and_insert_aqi, execution_date=20250327T120000, start_date=20250327T130007, end_date=20250327T130008
[2025-03-27T13:00:08.577+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-27T13:00:08.588+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
