[2025-03-27T16:00:00.155+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: insert_aqi_to_postgres.fetch_and_insert_aqi scheduled__2025-03-27T15:00:00+00:00 [queued]>
[2025-03-27T16:00:00.159+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: insert_aqi_to_postgres.fetch_and_insert_aqi scheduled__2025-03-27T15:00:00+00:00 [queued]>
[2025-03-27T16:00:00.160+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-03-27T16:00:00.165+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): fetch_and_insert_aqi> on 2025-03-27 15:00:00+00:00
[2025-03-27T16:00:00.167+0000] {standard_task_runner.py:60} INFO - Started process 3559 to run task
[2025-03-27T16:00:00.169+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'insert_aqi_to_postgres', 'fetch_and_insert_aqi', 'scheduled__2025-03-27T15:00:00+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/insert_aqi_to_db.py', '--cfg-path', '/tmp/tmpb3toel6d']
[2025-03-27T16:00:00.170+0000] {standard_task_runner.py:88} INFO - Job 55: Subtask fetch_and_insert_aqi
[2025-03-27T16:00:00.176+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-27T16:00:00.189+0000] {task_command.py:423} INFO - Running <TaskInstance: insert_aqi_to_postgres.fetch_and_insert_aqi scheduled__2025-03-27T15:00:00+00:00 [running]> on host 75125d84c351
[2025-03-27T16:00:00.219+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='insert_aqi_to_postgres' AIRFLOW_CTX_TASK_ID='fetch_and_insert_aqi' AIRFLOW_CTX_EXECUTION_DATE='2025-03-27T15:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-27T15:00:00+00:00'
[2025-03-27T16:00:00.512+0000] {insert_aqi_to_db.py:37} INFO - âœ… AQI in Bangkok: 118 at 2025-03-27 16:00:00.512121
[2025-03-27T16:00:00.527+0000] {base.py:83} INFO - Using connection ID 'postgres_conn' for task execution.
[2025-03-27T16:00:00.531+0000] {sql.py:450} INFO - Running statement: 
                INSERT INTO air_quality_data (city, aqi, timestamp_utc)
                VALUES (%s, %s, %s);
            , parameters: ('Bangkok', 118, datetime.datetime(2025, 3, 27, 16, 0, 0, 512121))
[2025-03-27T16:00:00.532+0000] {sql.py:459} INFO - Rows affected: 1
[2025-03-27T16:00:00.534+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-03-27T16:00:00.540+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=insert_aqi_to_postgres, task_id=fetch_and_insert_aqi, execution_date=20250327T150000, start_date=20250327T160000, end_date=20250327T160000
[2025-03-27T16:00:00.563+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-27T16:00:00.573+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
